version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
      - "50000:50000"
      - "22:22"
    volumes:
      - /home/user/jenkins_home:/var/jenkins_home
