apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  selector:
    app: webapp