# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

MAINTAINER jtuberquia07@outlook.com

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat

COPY target/java-tomcat-maven-example-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/